

export const membersData = [
    {
        email: 'Mohsen@test.com',
        userName: 'Mohsen',
        gender: 'male',
        dateOfBrith: '1992-3-5',
        name: 'Mohsen',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/user1.jpg'

    },
    {
        email: 'Ali@test.com',
        userName: 'Ali',
        gender: 'male',
        dateOfBrith: '1992-3-5',
        name: 'Ali',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/m1.JFIF'
    },
    {
        email: 'Zahra@test.com',
        userName: 'Zahra',
        gender: 'female',
        dateOfBrith: '1992-3-5',
        name: 'Zahra',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/f1.JFIF'
    },
    {
        email: 'mohammad@test.com',
        userName: 'mohammad',
        gender: 'male',
        dateOfBrith: '1992-3-5',
        name: 'mohammad',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/m2.JFIF'
    },
    {
        email: 'Negar@test.com',
        userName: 'Negar',
        gender: 'female',
        dateOfBrith: '1992-3-5',
        name: 'Negar',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/f2.JFIF'
    },
    {
        email: 'Jacob@test.com',
        userName: 'Jacob',
        gender: 'male',
        dateOfBrith: '1992-3-5',
        name: 'Jacob',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/m3.JFIF'
    },
    {
        email: 'Jason@test.com',
        userName: 'Jason',
        gender: 'male',
        dateOfBrith: '1992-3-5',
        name: 'Jason',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/m4.JFIF'
    },
    {
        email: 'James@test.com',
        userName: 'James',
        gender: 'male',
        dateOfBrith: '1992-3-5',
        name: 'James',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/m5.JFIF'
    },
    {
        email: 'Helen@test.com',
        userName: 'Helen',
        gender: 'female',
        dateOfBrith: '1992-3-5',
        name: 'Helen',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/f3.JFIF'
    },
    {
        email: 'Jenry@test.com',
        userName: 'Jenry',
        gender: 'male',
        dateOfBrith: '1992-3-5',
        name: 'Jenry',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/f4.JPG'
    },
    {
        email: 'lui@test.com',
        userName: 'lui',
        gender: 'female',
        dateOfBrith: '1992-3-5',
        name: 'lui',
        created: '2024-3-5',
        lastActive: '2024-5-7',
        description: 'heLLo I am new user of this platform',
        city: 'Tehran',
        country: 'Iran',
        image: '/images/f5.JFIF'
    },

]